#LIBFT_PATH	=	./libft/libft.h
#
#HEAD		= 	minishell.h
#
#SRC			=	main.c \
##				args.c \
##				funcs.c \
##				environments.c \
#
#LIBFT		=	$(LIBFT_PATH)
#
#NAME		=	minishell
#
#OBJS		=	$(SRCS:.c=.o)
#
#CC			=	gcc
#
#RM			= 	rm -rf
#
#CFLAGS		= 	-Wall -Wextra -Werror
#
#$(NAME)		:	$(OBJS)
#				$(MAKE) -C ./libft
#				$(CC) $(CFLAGS) $(OBJS) -o $(NAME)
#
#$(OBJS)	:	$(HEAD)
#
#all		:	$(NAME)
#
#clean		:
#				$(RM) $(OBJS)
#				$(MAKE) clean -C ./libft
#
#fclean		:	clean
#				$(RM) $(NAME)
#				$(RM) ./libft/libft.a
#
#re			:	fclean	all
#
#.PHONY		:	all clean fclean re
